name: Run GTest Suites

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install LLVM & Gtest
        run: |
          wget https://github.com/google/googletest/releases/download/v1.16.0/googletest-1.16.0.tar.gz
          tar xf googletest-1.16.0.tar.gz
          cd googletest-1.16.0/
          cmake -DBUILD_SHARED_LIBS=ON .
          make
          sudo make install
          sudo ldconfig -v | grep gtest
          sudo apt-get update
          sudo apt install libspdlog-dev llvm-14 g++
          cd ..
      - name: Build and run compilation tests (Code validity is not verified)
        run: |
          ./jimpilier.sh main.cpp
          ./runTests --gtest_filter=TestSyntax.*
      - name: Build and run program tests (Code is verified to be correct)
        run:
          |
          ./runTests --gtest_filter=TestCompiledCode.*
      - name: save cache
        id: cache-gtest-save
        uses: actions/cache/save@v4
        with: 
          path: |
            googletest-1.16.0
            llvm-cache
          key: ${{ runner.os }}-gtest-llvm