name: Caching gtest

on: 
  workflow_dispatch:
permissions:
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache gtest
      id: cache-gtest
      uses: actions/cache/save@v4
      with:
        path: |
          googletest-1.16.0
          llvm-cache
        key: ${{ runner.os }}-gtest
    - name: install gtest
      if: steps.cache-gtest.outputs.cache-hit != 'true'
      run: |
          sudo apt install -y cmake
          wget https://github.com/google/googletest/releases/download/v1.16.0/googletest-1.16.0.tar.gz
          tar xf googletest-1.16.0.tar.gz
          cd googletest-1.16.0/
          sudo apt-get update
          sudo apt-get install -y llvm-14 g++
          mkdir llvm-cache
          sudo cp /var/cache/apt/archives/llvm-14* ./llvm-cache
    - name: save cache
      id: cache-gtest-save
      uses: actions/cache/save@v4
      with: 
        path: |
          googletest-1.16.0
          llvm-cache
        key: ${{ runner.os }}-gtest-llvm